### ISSUE TITLE
CalendarDialog is unkown component

### ISSUE THREAD

**Issue by Nillrze** [mohammadhasanzadeh/yacalendar#3]
Hi

I add yacalender.pri to my .pro project
but when i use CalendarDialog , it's unknown

can you help me about it ?

**Comment by mohammadhasanzadeh** [comment]
Hi,
Are you added `yacalendar::register_calendar();` to your main.cpp!?
I can help you better if you copy your .pro file here.

**Comment by Nillrze** [comment]
yesi added yacalendar::register_calendar();

actually after i added (import "qrc:/") to my DatePickerPage file it works correctly

**Comment by mohammadhasanzadeh** [comment]
Normally not needed to add `import "qrc:/"` to your `qml` file, I don't know what happened exactly.

**Comment by Nillrze** [comment]
Hi,
I add the calendar to my project,
but after deploy on release mode , my app doesn't run
and get error for _module "Qt.labs.calendar" is not installed_

do you know why?
